version: '3'
services:
  db:
    image: mysql:5.6.40
    environment:
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp
      - MYSQL_ROOT_PASSWORD=myapp
    volumes:
      - ./docker/volumes/mysql/data:/var/lib/mysql:cached
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/containers/web/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
